name: eMart
description: Flutter eCommerce App using Firebase Firestore by T.Rangika

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 0.5.0+1
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.19.1 #help to use SVGs
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^5.0.0-dev.3
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^0.5.0+1
  image: ^2.0.7
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf

  assets:
    - assets/icons/
    - assets/images/



